/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoveterinario;



/**
 *
 * @author Nixon
 */
public class Proyecto extends javax.swing.JFrame {

    /**
     * Creates new form Proyecto
     */
    public Proyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jFrame1 = new javax.swing.JFrame();
        jMenuItem2 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        RbtnRegistroPersonas = new javax.swing.JMenuItem();
        RbtnResgistroClientes = new javax.swing.JRadioButtonMenuItem();
        RbtnRegistroMascotas = new javax.swing.JRadioButtonMenuItem();
        jMenu8 = new javax.swing.JMenu();
        RbtnRegistroCitas = new javax.swing.JRadioButtonMenuItem();
        RbtnRegistroFechasdeVacunacion = new javax.swing.JRadioButtonMenuItem();
        RbtnRegistroEnfermadades = new javax.swing.JRadioButtonMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nixon\\Desktop\\reglas.jpeg")); // NOI18N
        jMenu2.setText("Registro Cliente");
        jMenu2.add(jSeparator1);

        RbtnRegistroPersonas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.CTRL_MASK));
        RbtnRegistroPersonas.setText("Registro Personas");
        RbtnRegistroPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnRegistroPersonasActionPerformed(evt);
            }
        });
        jMenu2.add(RbtnRegistroPersonas);

        RbtnResgistroClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.CTRL_MASK));
        RbtnResgistroClientes.setSelected(true);
        RbtnResgistroClientes.setText("Registro Clientes");
        RbtnResgistroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnResgistroClientesActionPerformed(evt);
            }
        });
        jMenu2.add(RbtnResgistroClientes);

        RbtnRegistroMascotas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_UP, java.awt.event.InputEvent.CTRL_MASK));
        RbtnRegistroMascotas.setSelected(true);
        RbtnRegistroMascotas.setText("Registro Mascotas");
        RbtnRegistroMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnRegistroMascotasActionPerformed(evt);
            }
        });
        jMenu2.add(RbtnRegistroMascotas);

        jMenuBar1.add(jMenu2);

        jMenu8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nixon\\Desktop\\mascota.jpeg")); // NOI18N
        jMenu8.setText("Registro Citas");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        RbtnRegistroCitas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, 0));
        RbtnRegistroCitas.setSelected(true);
        RbtnRegistroCitas.setText("Registro Citas");
        RbtnRegistroCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnRegistroCitasActionPerformed(evt);
            }
        });
        jMenu8.add(RbtnRegistroCitas);

        RbtnRegistroFechasdeVacunacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, 0));
        RbtnRegistroFechasdeVacunacion.setSelected(true);
        RbtnRegistroFechasdeVacunacion.setText("Registro Fechas de Vacunacion");
        RbtnRegistroFechasdeVacunacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnRegistroFechasdeVacunacionActionPerformed(evt);
            }
        });
        jMenu8.add(RbtnRegistroFechasdeVacunacion);

        RbtnRegistroEnfermadades.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, 0));
        RbtnRegistroEnfermadades.setSelected(true);
        RbtnRegistroEnfermadades.setText("Registro Enfermedades ");
        RbtnRegistroEnfermadades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnRegistroEnfermadadesActionPerformed(evt);
            }
        });
        jMenu8.add(RbtnRegistroEnfermadades);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbtnRegistroPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnRegistroPersonasActionPerformed
          
         RegistroPersonas regis = new RegistroPersonas();
         this.escritorio.add(regis);
         regis.show();
           
    }//GEN-LAST:event_RbtnRegistroPersonasActionPerformed

    private void RbtnRegistroEnfermadadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnRegistroEnfermadadesActionPerformed
      RegistroEnfermedades enferme = new RegistroEnfermedades();
      this.escritorio.add(enferme);
      enferme.show();
    }//GEN-LAST:event_RbtnRegistroEnfermadadesActionPerformed

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
        
    }//GEN-LAST:event_jMenu8ActionPerformed

    private void RbtnResgistroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnResgistroClientesActionPerformed
        RegistroClientes clien = new RegistroClientes();
         this.escritorio.add(clien);
         clien.show();
    }//GEN-LAST:event_RbtnResgistroClientesActionPerformed

    private void RbtnRegistroMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnRegistroMascotasActionPerformed
        RegistroMascotas masco = new RegistroMascotas();
         this.escritorio.add(masco);
         masco.show();
    }//GEN-LAST:event_RbtnRegistroMascotasActionPerformed

    private void RbtnRegistroCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnRegistroCitasActionPerformed
        RegistroCitas cita = new RegistroCitas();
      this.escritorio.add(cita);
      cita.show();
    }//GEN-LAST:event_RbtnRegistroCitasActionPerformed

    private void RbtnRegistroFechasdeVacunacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnRegistroFechasdeVacunacionActionPerformed
        RegistrodeFechasdeVacunacion vacuna = new RegistrodeFechasdeVacunacion();
        this.escritorio.add(vacuna);
        vacuna.show();
    }//GEN-LAST:event_RbtnRegistroFechasdeVacunacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem RbtnRegistroCitas;
    private javax.swing.JRadioButtonMenuItem RbtnRegistroEnfermadades;
    private javax.swing.JRadioButtonMenuItem RbtnRegistroFechasdeVacunacion;
    private javax.swing.JRadioButtonMenuItem RbtnRegistroMascotas;
    private javax.swing.JMenuItem RbtnRegistroPersonas;
    private javax.swing.JRadioButtonMenuItem RbtnResgistroClientes;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
